// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPGccSRaccaug7LPL4kaYrkMcz-j3F6c',
    appId: '1:814424616458:web:c9d5066b7d146cb83e79f3',
    messagingSenderId: '814424616458',
    projectId: 'chatapptuto-40fce',
    authDomain: 'chatapptuto-40fce.firebaseapp.com',
    storageBucket: 'chatapptuto-40fce.appspot.com',
    measurementId: 'G-44XCGFZ56L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxrjlOIHLY0Y20Kbf7flgHFd_IUkvPtU',
    appId: '1:814424616458:android:bdffc35343eb89703e79f3',
    messagingSenderId: '814424616458',
    projectId: 'chatapptuto-40fce',
    storageBucket: 'chatapptuto-40fce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9kEe0trrw_RhLXI5nu1BCF8opmdp-qLA',
    appId: '1:814424616458:ios:2bbf439614cfd3e53e79f3',
    messagingSenderId: '814424616458',
    projectId: 'chatapptuto-40fce',
    storageBucket: 'chatapptuto-40fce.appspot.com',
    iosBundleId: 'com.chatuto.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtPGccSRaccaug7LPL4kaYrkMcz-j3F6c',
    appId: '1:814424616458:web:df9d023081fb62e23e79f3',
    messagingSenderId: '814424616458',
    projectId: 'chatapptuto-40fce',
    authDomain: 'chatapptuto-40fce.firebaseapp.com',
    storageBucket: 'chatapptuto-40fce.appspot.com',
    measurementId: 'G-4QB36VX8K6',
  );

}